# Generated by Django 5.2.4 on 2025-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
