# Generated by Django 5.2.4 on 2025-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
    ]
