# Generated by Django 5.2.4 on 2025-08-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
