# Generated by Django 5.2.4 on 2025-09-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_student_branch_booking_student_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotedgroundbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alloted_bookings', to='booking.booking'),
        ),
    ]
