# Generated by Django 5.2.4 on 2025-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_allotedgroundbooking_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_email',
            field=models.EmailField(default='example@student.com', max_length=254),
            preserve_default=False,
        ),
    ]
