# Generated by Django 5.2.4 on 2025-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
