# Generated by Copilot on 2025-10-13
from django.db import migrations, models
import django.db.models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_sport'),
    ]

    operations = [
        # Remove old unique constraint if exists (name may vary in some DBs)
        migrations.RunSQL(
            sql=(
                "ALTER TABLE booking_booking DROP CONSTRAINT IF EXISTS uniq_approved_slot;"
            ),
            reverse_sql=(
                # Can't easily recreate without full definition; leave no-op
                ""
            ),
        ),
        # Remove old index if exists
        migrations.RunSQL(
            sql=(
                "DROP INDEX IF EXISTS idx_slot_status;"
            ),
            reverse_sql=(
                ""
            ),
        ),
        # Add new index explicitly for some DBs (Django will create from model too)
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS idx_sport_date_slot_status ON booking_booking (date, sport, time_slot, status);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS idx_sport_date_slot_status;"
            ),
        ),
        # Note: The UniqueConstraint with condition is defined in the model Meta and will be applied by makemigrations/migrate.
    ]
