# Generated by Django 5.2.4 on 2025-10-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_update_fcfs_constraints'),
    ]

    operations = [
        migrations.RunSQL(
            sql=("CREATE INDEX IF NOT EXISTS idx_sport_date_slot_status ON booking_booking (date, sport, time_slot, status);"),
            reverse_sql=("DROP INDEX IF EXISTS idx_sport_date_slot_status;"),
        ),
        migrations.RunSQL(
            sql=("CREATE INDEX IF NOT EXISTS idx_created_at ON booking_booking (created_at);"),
            reverse_sql=("DROP INDEX IF EXISTS idx_created_at;"),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Approved')), fields=('date', 'sport', 'time_slot'), name='uniq_approved_sport_slot'),
        ),
    ]
