# Generated by Django 5.2.11 on 2026-02-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'sport', 'time_slot', 'status'], name='idx_sport_date_slot_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
    ]
