# Generated by Django 5.2.11 on 2026-02-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_otpverification_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='roll_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
